-- MySQL Script generated by MySQL Workbench
-- Mon May 12 19:35:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema modelagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelagem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `modelagem` ;

-- -----------------------------------------------------
-- Table `modelagem`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`municipio` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`municipio` (
  `id_municipio` INT NOT NULL,
  `sigla_uf` CHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`demografia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`demografia` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`demografia` (
  `ano` YEAR NOT NULL,
  `id_municipio` INT NOT NULL,
  `populacao_urbana` INT NULL DEFAULT NULL,
  `populacao_urbana_residente_agua` INT NULL DEFAULT NULL,
  `populacao_urbana_atendida_agua` INT NULL DEFAULT NULL,
  `populacao_urbana_residente_esgoto` INT NULL DEFAULT NULL,
  `populacao_urbana_atendida_esgoto` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ano`, `id_municipio`),
  INDEX `id_municipio` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `demografia_ibfk_1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `modelagem`.`municipio` (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`despesas` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`despesas` (
  `ano` YEAR NOT NULL,
  `id_municipio` INT NOT NULL,
  `despesa_pessoal` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_produto_quimico` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_energia` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_servico_terceiro` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_exploracao` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesas_juros_divida` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_total_servico` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_ativo` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_agua_importada` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_fiscal` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_fiscal_nao_computada` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_exploracao_outro` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_servico_outro` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_amortizacao_divida` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesas_juros_divida_excecao` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_divida_variacao` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_divida_total` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_esgoto_exportado` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_capitalizavel_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_capitalizavel_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  `despesa_capitalizavel_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ano`, `id_municipio`),
  INDEX `id_municipio` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `despesas_ibfk_1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `modelagem`.`municipio` (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`financeiro_geral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`financeiro_geral` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`financeiro_geral` (
  `ano` YEAR NOT NULL,
  `id_municipio` INT NOT NULL,
  `receita_operacional_direta` DECIMAL(15,2) NULL DEFAULT NULL,
  `receita_operacional_direta_agua` DECIMAL(15,2) NULL DEFAULT NULL,
  `receita_operacional_direta_esgoto` DECIMAL(15,2) NULL DEFAULT NULL,
  `receita_operacional_indireta` DECIMAL(15,2) NULL DEFAULT NULL,
  `receita_operacional_direta_agua_exportada` DECIMAL(15,2) NULL DEFAULT NULL,
  `receita_operacional` DECIMAL(15,2) NULL DEFAULT NULL,
  `receita_operacional_direta_esgoto_importado` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ano`, `id_municipio`),
  INDEX `id_municipio` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `financeiro_geral_ibfk_1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `modelagem`.`municipio` (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`indices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`indices` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`indices` (
  `ano` YEAR NOT NULL,
  `id_municipio` INT NOT NULL,
  `indice_agua_ligacao` DECIMAL(5,2) NULL DEFAULT NULL,
  `indice_hidrometracao` DECIMAL(5,2) NULL DEFAULT NULL,
  `indice_macromedicao` DECIMAL(5,2) NULL DEFAULT NULL,
  `indice_perda_faturamento` DECIMAL(5,2) NULL DEFAULT NULL,
  `indice_coleta_esgoto` DECIMAL(5,2) NULL DEFAULT NULL,
  `indice_tratamento_esgoto` DECIMAL(5,2) NULL DEFAULT NULL,
  `indice_consumo_agua` DECIMAL(5,2) NULL DEFAULT NULL,
  `indice_fluoretacao_agua` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ano`, `id_municipio`),
  INDEX `id_municipio` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `indices_ibfk_1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `modelagem`.`municipio` (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`infraestrutura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`infraestrutura` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`infraestrutura` (
  `ano` YEAR NOT NULL,
  `id_municipio` INT NOT NULL,
  `extensao_rede_agua` DECIMAL(15,2) NULL DEFAULT NULL,
  `extensao_rede_esgoto` DECIMAL(15,2) NULL DEFAULT NULL,
  `quantidade_sede_municipal_agua` INT NULL DEFAULT NULL,
  `quantidade_sede_municipal_esgoto` INT NULL DEFAULT NULL,
  `quantidade_localidade_agua` INT NULL DEFAULT NULL,
  `quantidade_localidade_esgoto` INT NULL DEFAULT NULL,
  `quantidade_ligacao_ativa_agua` INT NULL DEFAULT NULL,
  `quantidade_ligacao_ativa_esgoto` INT NULL DEFAULT NULL,
  `volume_agua_produzido` DECIMAL(15,2) NULL DEFAULT NULL,
  `volume_esgoto_tratado` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ano`, `id_municipio`),
  INDEX `id_municipio` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `infraestrutura_ibfk_1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `modelagem`.`municipio` (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`investimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`investimentos` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`investimentos` (
  `ano` YEAR NOT NULL,
  `id_municipio` INT NOT NULL,
  `investimento_agua_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_esgoto_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_outro_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_proprio_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_oneroso_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_nao_oneroso_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_total_prestador` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_agua_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_esgoto_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_outro_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_proprio_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_oneroso_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_nao_oneroso_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_total_municipio` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_agua_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_esgoto_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_outro_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_proprio_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_oneroso_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_recurso_nao_oneroso_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  `investimento_total_estado` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ano`, `id_municipio`),
  INDEX `id_municipio` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `investimentos_ibfk_1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `modelagem`.`municipio` (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
